# Generated by Django 4.1.7 on 2023-09-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
